pull_request_rules:
  - name: Automatic assign & labeling
    conditions:
      - -merged
      - -closed
      - base=main
    actions:
      assign:
        add_users:
          - "{{author}}"
      label:
        add:
          - "#697"
